// autogenerated file - do not edit

#ifndef PROPHET_NNUE_CONFIG_H
#define PROPHET_NNUE_CONFIG_H

#define NNUE_INPUT_SIZE 768
#define NNUE_L1_SIZE 8
#define NNUE_L2_SIZE 8

#endif // PROPHET_NNUE_CONFIG_H
