#ifndef NNUE_CONFIG_H
#define NNUE_CONFIG_H

#define NNUE_INPUT_SIZE 768
#define NNUE_L1_SIZE 256
#define NNUE_L2_SIZE 8
#define NNUE_FT_SCALE 127
#define NNUE_WEIGHT_SCALE 64
#define NNUE_WEIGHT_SHIFT 6
#define NNUE_OUTPUT_SCALE 410
#endif // NNUE_CONFIG_H
